commom: &common
  HOST: 'localhost.dev'
  SMTP_USER: 'rebisall@gmail.com'
  SMTP_PASSWORD: 'n-Khqe37NGroZTwuB25HiA'

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  HOST: 'helperchat.com'
  SMTP_USER: 'rebisall@gmail.com'
  SMTP_PASSWORD: 'AVLbNXNvpAnLZ9VGmE_61A'
