require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArchiveJidPrefsController do

  # This should return the minimal set of attributes required to create a valid
  # ArchiveJidPref. As you add validations to ArchiveJidPref, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "with_user" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArchiveJidPrefsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all archive_jid_prefs as @archive_jid_prefs" do
      archive_jid_pref = ArchiveJidPref.create! valid_attributes
      get :index, {}, valid_session
      assigns(:archive_jid_prefs).should eq([archive_jid_pref])
    end
  end

  describe "GET show" do
    it "assigns the requested archive_jid_pref as @archive_jid_pref" do
      archive_jid_pref = ArchiveJidPref.create! valid_attributes
      get :show, {:id => archive_jid_pref.to_param}, valid_session
      assigns(:archive_jid_pref).should eq(archive_jid_pref)
    end
  end

  describe "GET new" do
    it "assigns a new archive_jid_pref as @archive_jid_pref" do
      get :new, {}, valid_session
      assigns(:archive_jid_pref).should be_a_new(ArchiveJidPref)
    end
  end

  describe "GET edit" do
    it "assigns the requested archive_jid_pref as @archive_jid_pref" do
      archive_jid_pref = ArchiveJidPref.create! valid_attributes
      get :edit, {:id => archive_jid_pref.to_param}, valid_session
      assigns(:archive_jid_pref).should eq(archive_jid_pref)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArchiveJidPref" do
        expect {
          post :create, {:archive_jid_pref => valid_attributes}, valid_session
        }.to change(ArchiveJidPref, :count).by(1)
      end

      it "assigns a newly created archive_jid_pref as @archive_jid_pref" do
        post :create, {:archive_jid_pref => valid_attributes}, valid_session
        assigns(:archive_jid_pref).should be_a(ArchiveJidPref)
        assigns(:archive_jid_pref).should be_persisted
      end

      it "redirects to the created archive_jid_pref" do
        post :create, {:archive_jid_pref => valid_attributes}, valid_session
        response.should redirect_to(ArchiveJidPref.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved archive_jid_pref as @archive_jid_pref" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveJidPref.any_instance.stub(:save).and_return(false)
        post :create, {:archive_jid_pref => { "with_user" => "invalid value" }}, valid_session
        assigns(:archive_jid_pref).should be_a_new(ArchiveJidPref)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveJidPref.any_instance.stub(:save).and_return(false)
        post :create, {:archive_jid_pref => { "with_user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested archive_jid_pref" do
        archive_jid_pref = ArchiveJidPref.create! valid_attributes
        # Assuming there are no other archive_jid_prefs in the database, this
        # specifies that the ArchiveJidPref created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArchiveJidPref.any_instance.should_receive(:update).with({ "with_user" => "MyString" })
        put :update, {:id => archive_jid_pref.to_param, :archive_jid_pref => { "with_user" => "MyString" }}, valid_session
      end

      it "assigns the requested archive_jid_pref as @archive_jid_pref" do
        archive_jid_pref = ArchiveJidPref.create! valid_attributes
        put :update, {:id => archive_jid_pref.to_param, :archive_jid_pref => valid_attributes}, valid_session
        assigns(:archive_jid_pref).should eq(archive_jid_pref)
      end

      it "redirects to the archive_jid_pref" do
        archive_jid_pref = ArchiveJidPref.create! valid_attributes
        put :update, {:id => archive_jid_pref.to_param, :archive_jid_pref => valid_attributes}, valid_session
        response.should redirect_to(archive_jid_pref)
      end
    end

    describe "with invalid params" do
      it "assigns the archive_jid_pref as @archive_jid_pref" do
        archive_jid_pref = ArchiveJidPref.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveJidPref.any_instance.stub(:save).and_return(false)
        put :update, {:id => archive_jid_pref.to_param, :archive_jid_pref => { "with_user" => "invalid value" }}, valid_session
        assigns(:archive_jid_pref).should eq(archive_jid_pref)
      end

      it "re-renders the 'edit' template" do
        archive_jid_pref = ArchiveJidPref.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveJidPref.any_instance.stub(:save).and_return(false)
        put :update, {:id => archive_jid_pref.to_param, :archive_jid_pref => { "with_user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested archive_jid_pref" do
      archive_jid_pref = ArchiveJidPref.create! valid_attributes
      expect {
        delete :destroy, {:id => archive_jid_pref.to_param}, valid_session
      }.to change(ArchiveJidPref, :count).by(-1)
    end

    it "redirects to the archive_jid_prefs list" do
      archive_jid_pref = ArchiveJidPref.create! valid_attributes
      delete :destroy, {:id => archive_jid_pref.to_param}, valid_session
      response.should redirect_to(archive_jid_prefs_url)
    end
  end

end
