require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArchiveMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # ArchiveMessage. As you add validations to ArchiveMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "utc" => "2013-09-22 19:18:27" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArchiveMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all archive_messages as @archive_messages" do
      archive_message = ArchiveMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:archive_messages).should eq([archive_message])
    end
  end

  describe "GET show" do
    it "assigns the requested archive_message as @archive_message" do
      archive_message = ArchiveMessage.create! valid_attributes
      get :show, {:id => archive_message.to_param}, valid_session
      assigns(:archive_message).should eq(archive_message)
    end
  end

  describe "GET new" do
    it "assigns a new archive_message as @archive_message" do
      get :new, {}, valid_session
      assigns(:archive_message).should be_a_new(ArchiveMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested archive_message as @archive_message" do
      archive_message = ArchiveMessage.create! valid_attributes
      get :edit, {:id => archive_message.to_param}, valid_session
      assigns(:archive_message).should eq(archive_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArchiveMessage" do
        expect {
          post :create, {:archive_message => valid_attributes}, valid_session
        }.to change(ArchiveMessage, :count).by(1)
      end

      it "assigns a newly created archive_message as @archive_message" do
        post :create, {:archive_message => valid_attributes}, valid_session
        assigns(:archive_message).should be_a(ArchiveMessage)
        assigns(:archive_message).should be_persisted
      end

      it "redirects to the created archive_message" do
        post :create, {:archive_message => valid_attributes}, valid_session
        response.should redirect_to(ArchiveMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved archive_message as @archive_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveMessage.any_instance.stub(:save).and_return(false)
        post :create, {:archive_message => { "utc" => "invalid value" }}, valid_session
        assigns(:archive_message).should be_a_new(ArchiveMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveMessage.any_instance.stub(:save).and_return(false)
        post :create, {:archive_message => { "utc" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested archive_message" do
        archive_message = ArchiveMessage.create! valid_attributes
        # Assuming there are no other archive_messages in the database, this
        # specifies that the ArchiveMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArchiveMessage.any_instance.should_receive(:update).with({ "utc" => "2013-09-22 19:18:27" })
        put :update, {:id => archive_message.to_param, :archive_message => { "utc" => "2013-09-22 19:18:27" }}, valid_session
      end

      it "assigns the requested archive_message as @archive_message" do
        archive_message = ArchiveMessage.create! valid_attributes
        put :update, {:id => archive_message.to_param, :archive_message => valid_attributes}, valid_session
        assigns(:archive_message).should eq(archive_message)
      end

      it "redirects to the archive_message" do
        archive_message = ArchiveMessage.create! valid_attributes
        put :update, {:id => archive_message.to_param, :archive_message => valid_attributes}, valid_session
        response.should redirect_to(archive_message)
      end
    end

    describe "with invalid params" do
      it "assigns the archive_message as @archive_message" do
        archive_message = ArchiveMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => archive_message.to_param, :archive_message => { "utc" => "invalid value" }}, valid_session
        assigns(:archive_message).should eq(archive_message)
      end

      it "re-renders the 'edit' template" do
        archive_message = ArchiveMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArchiveMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => archive_message.to_param, :archive_message => { "utc" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested archive_message" do
      archive_message = ArchiveMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => archive_message.to_param}, valid_session
      }.to change(ArchiveMessage, :count).by(-1)
    end

    it "redirects to the archive_messages list" do
      archive_message = ArchiveMessage.create! valid_attributes
      delete :destroy, {:id => archive_message.to_param}, valid_session
      response.should redirect_to(archive_messages_url)
    end
  end

end
